version: 2
updates:
- package-ecosystem: nuget
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: FluentFTP
    versions:
    - 33.0.3
    - 33.1.1
    - 33.1.3
    - 33.1.4
    - 33.1.5
    - 33.1.6
    - 33.1.7
  - dependency-name: Google.Apis.Core
    versions:
    - 1.49.0
    - 1.50.0
  - dependency-name: System.Collections.Immutable
    versions:
    - 5.0.0
